server:
  port: 9527

spring:
  kafka:
    bootstrap-servers: hdspdemo003:6667
    listener:
      concurrency: 4
    consumer:
      client-id: neo4j_app
      max-poll-records: 200
      auto-offset-reset: earliest
  data:
    neo4j:
      uri: bolt://172.23.16.66:7687
      username: neo4j
      password: 123456

logging:
  level:
    org.isaac.lineage: ${LOGGING_LEVEL:debug}
